### ISSUE TITLE
Documentation isn't clear on 4096-bit keys

### ISSUE THREAD

**Issue by chizou** [awsdocs/aws-certificate-user-guide#1]
This documentation makes it seem like ACM supports 4096-bit keys, which it does, except when it comes to supporting them on ALB/CLBs. 

> Note that integrated services allow only algorithms and key sizes they support to be associated with their resources. Further, their support differs depending on whether the certificate is imported into IAM or into ACM. For more information, see the documentation for each service.

Is meant to clarify that, but it's pretty ambiguous. Not even our enterprise support engineer understood that to mean that I have to use IAM to upload a 4096-bit key.

I would like to add to the documentation that Load Balancers specifically can't support 4096-bit keys from ACM, but it seems like such a one-off bullet to add. Not to mention that bullets in this repo don't seem to match up with the corresponding page on production: https://docs.aws.amazon.com/acm/latest/userguide/import-certificate-prerequisites.html

Please advise

**Comment by chizou** [comment]
Based on a response from our support ticket, it seems that there are other services besides ALBs and CLBs that also can't support 4096-bit keys. I don't know how to find this info out, but I think it'd be valuable to add if for no other reason than I don't think any general user knows how to find this out.

**Comment by pettibon** [comment]
You may be looking at an older version of the docs. GitHub isn't updated often because updating is a manual process and error-prone. 

I recently copied the table you mentioned from the import-certificate-prerequisites.html page into the https://docs.aws.amazon.com/acm/latest/userguide/acm-certificate.html page. ACM does indeed support 4096-bit keys and other algorithms (mainly EC), but the primary services that are integrated with ACM (ELB and CF) might not. Their support can change at any time. Therefore the ACM docs can't tell you what the integrated services support because maintenance of the ACM docs would be effectively impossible. The docs can only link you to their SSL tables, and you have to decipher those tables. Hit the links and go to their SSL tables to determine what ELB and CF support. 

You can import 3rd party certificates into ACM, but if you want to use those certs for SSL/TLS with ELB or CF, they must specify an algorithm that ELB or CF support. Again, you'd need to go to ELB or CF to find out. You don't have to use 3rd party certificates with ELB or CF. Maybe you have other reasons for importing a certificate into the ACM infrastructure.

Other services support other algorithms, but we really only currently care about ELB and CF. ACM supports additional key sizes and algorithms for future expansion and for private certificates that are signed by a private CA but managed within the ACM environment.
